version: '3'
services:
  mpd:
    build: .
    container_name: mpd
    ports:
      - "6600:6600"
      - "8000:8000"
    volumes:
      - ./music:/music:ro
      - ./playlists:/playlists
      - .//var/lib/mpd
      - ./mpd.conf:/etc/mpd.conf:ro
    restart: always
